import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, BadgeCheck, Binary, Download, Fingerprint, Github, KeyRound, Linkedin, Mail, MapPin, Menu, Network, Radar, Terminal, Users } from "lucide-react";
import { achievements, apiEvidence, cases, ctfBadges, downloads, labItems, navItems, philosophy, projectEvidence, proof, recruiterScan, stack, systemStatus, timeline, trail, waskiZone, writeupPosts, writeups } from "@/lib/portfolio-data";
import { ApiSimulator, CommandPalette, ContactIntentSelector, GitHubActivity, HackChallenge, ModeAwareHeroText, ModeSwitcher, TypedTerminal } from "@/components/InteractiveCockpit";
import { AnimatedApiFlow, CertificateActivitySection, ContactForm, DashboardPreviewLink, ProjectComparisonMatrix, ScreenshotLightbox } from "@/components/PortfolioEnhancements";
import { VisualEffects } from "@/components/VisualEffects";

export default function Home() {
  return (
    <main className="scanline relative overflow-hidden">
      <VisualEffects />
      <CommandPalette />
      <div className="cyber-grid pointer-events-none absolute inset-x-0 top-0 h-[860px]" />
      <header className="sticky top-0 z-40 border-b border-white/10 bg-ink/86 backdrop-blur-xl"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="#identity" className="flex min-w-0 items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center border border-mint/40 bg-mint/10 text-mint"><Terminal size={20} /></span><span><span className="block font-mono text-sm text-mint">khophisnow</span><span className="block text-xs text-white/55">secure systems cockpit</span></span></a><div className="hidden items-center gap-5 text-sm text-white/68 xl:flex">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase().replace(" ", "-")}`} className="hover:text-mint">{item}</a>)}</div><div className="hidden items-center gap-3 md:flex"><a href="https://github.com/khophisnow" target="_blank" rel="noreferrer" className="flex size-10 items-center justify-center border border-white/12 text-white/70 transition hover:border-cyan hover:text-cyan"><Github size={18} /></a><a href="/cv/somuah-julius-software-developer-cv-2026.pdf" className="inline-flex items-center gap-2 border border-mint/40 px-4 py-2 text-sm font-semibold text-mint transition hover:bg-mint hover:text-ink"><Download size={16} />CV</a></div><details className="relative xl:hidden"><summary className="flex size-10 cursor-pointer items-center justify-center border border-white/12 text-white/80"><Menu size={19} /></summary><div className="absolute right-0 top-12 w-64 border border-white/12 bg-ink p-3 shadow-terminal">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase().replace(" ", "-")}`} className="block border-b border-white/8 px-3 py-3 text-sm text-white/72 last:border-b-0 hover:text-mint">{item}</a>)}</div></details></nav></header>

      <section id="identity" className="relative mx-auto grid min-h-[calc(100vh-73px)] max-w-7xl items-center gap-12 px-5 py-14 lg:grid-cols-[1fr_0.94fr] lg:px-8"><ModeAwareHeroText /><aside className="grid gap-4"><figure className="panel-glow relative overflow-hidden border border-white/10 bg-panel/75 p-3"><Image src="/images/operator-cockpit.jpeg" alt="KhophiSnow operator visual" width={1536} height={864} priority className="aspect-video w-full object-cover" /><figcaption className="absolute bottom-5 left-5 border border-mint/30 bg-ink/80 px-3 py-2 font-mono text-xs text-mint backdrop-blur">operator visual</figcaption></figure><TypedTerminal /><div className="grid gap-3 sm:grid-cols-3"><MiniMetric icon={<Fingerprint size={16} />} label="Auth" value="JWT / RBAC" /><MiniMetric icon={<Network size={16} />} label="APIs" value="REST / OpenAPI" /><MiniMetric icon={<Radar size={16} />} label="Security" value="CTF / labs" /></div></aside></section>
      <section className="border-y border-white/10 bg-white/[0.025]"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-3 px-5 py-10 sm:grid-cols-2 lg:grid-cols-4 lg:px-8">{proof.map((item) => <div key={item.label} className="border border-white/10 bg-ink/55 p-5"><p className="font-mono text-4xl font-black text-mint">{item.value}</p><p className="mt-2 text-sm font-bold text-white/78">{item.label}</p><p className="mt-2 text-xs leading-5 text-white/45">{item.detail}</p></div>)}</div></section>
      <ModeSwitcher />
      <section id="status" className="border-y border-white/10 bg-white/[0.025]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionTitle eyebrow="Live system status" title="The cockpit view of what I am building, practicing, and teaching" /><div className="mt-5 max-w-2xl text-sm leading-7 text-white/62"><p className="mode-copy mode-copy-builder">Builder view: the focus here is delivery, system clarity, API structure, and product readiness.</p><p className="mode-copy mode-copy-breaker">Breaker view: the focus here is exposure, weak boundaries, logs, access control, and defensive review.</p><p className="mode-copy mode-copy-trainer">Trainer view: the focus here is mentoring, learning paths, practical teaching, and community impact.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{systemStatus.map((item) => { const Icon = item.icon; return <article key={item.label} className="border border-white/10 bg-panel/70 p-5"><Icon className="text-mint" /><p className="mt-4 font-mono text-xs uppercase text-white/42">{item.label}</p><h3 className="mt-1 text-2xl font-black text-white">{item.value}</h3><p className="mt-3 text-xs leading-5 text-white/55">{item.detail}</p></article>; })}</div></div></section>
      <section id="case-files" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionTitle eyebrow="Case files" title="Products where the backend actually matters" /><div className="mt-10 space-y-5">{cases.map((project) => <article key={project.name} className="grid gap-6 border border-white/10 bg-panel/78 p-5 transition hover:border-cyan/45 lg:grid-cols-[0.55fr_1fr]"><div className="border border-white/10 bg-black/25 p-5"><p className="font-mono text-xs text-amber">{project.code} / {project.year}</p><h3 className="mt-3 text-3xl font-black text-white">{project.name}</h3><p className="mt-2 text-sm font-semibold text-cyan">{project.role}</p><div className="mt-6 grid gap-2 sm:grid-cols-2 lg:grid-cols-1">{project.impact.map((item) => <span key={item} className="border border-white/10 bg-white/[0.035] px-3 py-2 font-mono text-xs text-white/64">{item}</span>)}</div></div><div className="flex flex-col p-1"><p className="text-sm leading-7 text-white/68">{project.brief}</p><BackendModuleMap modules={project.modules} /><div className="mt-6 flex flex-wrap gap-2">{project.stack.map((item) => <span key={item} className="border border-white/10 bg-white/[0.04] px-2.5 py-1.5 font-mono text-xs text-white/70">{item}</span>)}</div><div className="mt-auto flex flex-wrap gap-4 pt-6"><Link href={`/case-files/${project.slug}`} className="inline-flex items-center gap-2 text-sm font-bold text-mint hover:text-white">Full case study<ArrowUpRight size={15} /></Link>{project.links.map((link) => <a key={link.href} href={link.href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-bold text-cyan hover:text-white">{link.label}<ArrowUpRight size={15} /></a>)}</div></div></article>)}</div></section>
      <AnimatedApiFlow />
      <ProjectComparisonMatrix />
      <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionTitle eyebrow="Project proof" title="Evidence that the systems were designed with boundaries" /><div className="mt-10 grid gap-4 md:grid-cols-2">{projectEvidence.map((item) => <article key={item.project + item.label} className="border border-white/10 bg-panel/70 p-5"><p className="font-mono text-xs uppercase text-cyan">{item.project}</p><h3 className="mt-3 text-xl font-black text-white">{item.label}</h3><p className="mt-3 text-sm leading-7 text-white/62">{item.detail}</p></article>)}</div></section>
      <section id="evidence" className="border-y border-white/10 bg-white/[0.025]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[0.9fr_1.1fr] lg:px-8"><div><SectionTitle eyebrow="API evidence" title="Proof that backend work is more than a list of tools" /><div className="mt-8 grid gap-3 sm:grid-cols-2">{apiEvidence.map((item) => { const Icon = item.icon; return <div key={item.label} className="border border-white/10 bg-panel/70 p-4"><Icon className="text-cyan" size={18} /><p className="mt-3 font-bold text-white">{item.label}</p><p className="mt-2 text-xs leading-5 text-white/55">{item.detail}</p></div>; })}</div></div><ApiSimulator /></div></section>
      <section id="stack" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><SectionTitle eyebrow="Toolbox" title="The tools behind the builder and the breaker" /><div className="mt-5 max-w-2xl text-sm leading-7 text-white/62"><p className="mode-copy mode-copy-builder">Builder language: APIs, schemas, modules, tests, documentation, and stable integrations.</p><p className="mode-copy mode-copy-breaker">Breaker language: recon, enumeration, auth boundaries, privilege paths, and attack surface thinking.</p><p className="mode-copy mode-copy-trainer">Trainer language: roadmaps, fundamentals, debugging support, project-based learning, and confidence building.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{stack.map((group) => { const Icon = group.icon; return <div key={group.area} className="border border-white/10 bg-ink/70 p-5 transition hover:border-amber/45"><Icon className="text-cyan" /><h3 className="mt-5 text-xl font-black text-white">{group.area}</h3><div className="mt-5 flex flex-wrap gap-2">{group.tools.map((tool) => <span key={tool} className="bg-white/[0.055] px-2.5 py-1.5 text-xs text-white/68">{tool}</span>)}</div></div>; })}</div></section>
      <section id="lab" className="border-y border-white/10 bg-ink/72"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[0.9fr_1.1fr] lg:px-8"><div><SectionTitle eyebrow="Security lab" title="Ethical hacking practice that changes how I code" /><p className="mt-6 max-w-xl text-sm leading-7 text-white/62">The lab side is not decoration. It is how I build instincts around enumeration, trust boundaries, weak auth, exposed routes, misconfiguration, privilege paths, and secure implementation.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{ctfBadges.map((badge) => { const Icon = badge.icon; return <div key={badge.title} className="border border-white/10 bg-panel/70 p-4"><Icon className="text-amber" size={18} /><p className="mt-3 font-bold text-white">{badge.title}</p><p className="mt-2 text-xs leading-5 text-white/55">{badge.detail}</p></div>; })}</div></div><div className="grid gap-3 sm:grid-cols-2">{labItems.map((item) => <div key={item} className="flex items-center gap-3 border border-white/10 bg-panel/70 p-4"><Binary className="shrink-0 text-mint" size={18} /><span className="text-sm text-white/72">{item}</span></div>)}<div className="border border-mint/25 bg-mint/10 p-4 sm:col-span-2"><p className="font-mono text-xs text-mint">security principle</p><p className="mt-2 text-sm leading-7 text-white/70">Offensive curiosity. Defensive discipline. Production responsibility.</p></div></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div><SectionTitle eyebrow="Threat models" title="I want project cards to show what could go wrong" /><p className="mt-5 text-sm leading-7 text-white/62">Each major project now has risk, control, and lesson cards so the security story is visible instead of implied.</p></div><div className="grid gap-4">{cases.flatMap((project) => project.threatModel.slice(0, 2).map((threat) => ({ ...threat, project: project.name }))).map((threat) => <div key={`${threat.project}-${threat.risk}`} className="border border-white/10 bg-panel/70 p-5"><p className="font-mono text-xs text-amber">{threat.project}</p><p className="mt-3 text-sm text-white/72"><span className="font-bold text-white">Risk:</span> {threat.risk}</p><p className="mt-2 text-sm text-white/72"><span className="font-bold text-mint">Control:</span> {threat.control}</p><p className="mt-2 text-xs leading-5 text-white/50">{threat.lesson}</p></div>)}</div></div></section>
      <section id="writeups" className="border-y border-white/10 bg-white/[0.025]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><SectionTitle eyebrow="Micro blog / writeups" title="A place for CTF notes, API security lessons, and backend breakdowns" /><Link href="/writeups" className="inline-flex items-center gap-2 border border-mint/30 px-4 py-3 font-bold text-mint hover:bg-mint hover:text-ink">Open writeup library<ArrowUpRight size={16} /></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{writeups.map((post, index) => <Link key={post.title} href={`/writeups/${writeupPosts[index].slug}`} className="block border border-white/10 bg-panel/70 p-5 hover:border-mint"><p className="font-mono text-xs text-cyan">{post.type} / {writeupPosts[index].readingTime}</p><h3 className="mt-3 text-xl font-black text-white">{post.title}</h3><p className="mt-4 text-sm leading-7 text-white/60">{post.detail}</p><div className="mt-4 flex flex-wrap gap-2">{writeupPosts[index].tags.map((tag) => <span key={tag} className="bg-white/[0.055] px-2 py-1 text-xs text-white/58">{tag}</span>)}</div></Link>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-2"><div><SectionTitle eyebrow="Security philosophy" title="The manifesto behind the interface" /><div className="mt-8 space-y-4">{philosophy.map((item) => <blockquote key={item} className="border-l-2 border-mint bg-panel/55 p-5 text-lg font-semibold leading-8 text-white/80">{item}</blockquote>)}</div></div><div><SectionTitle eyebrow="Recruiter/client scan" title="Quick signal for busy people" /><div className="mt-8 grid gap-3">{recruiterScan.map((item) => <div key={item.label} className="border border-white/10 bg-panel/70 p-4"><p className="font-mono text-xs uppercase text-mint">{item.label}</p><p className="mt-2 text-sm leading-6 text-white/70">{item.value}</p></div>)}</div></div></div></section>
      <section className="border-y border-white/10 bg-ink/72"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[0.85fr_1.15fr] lg:px-8"><SectionTitle eyebrow="Timeline" title="From curiosity to security-minded backend engineering" /><div className="space-y-4">{timeline.map((item) => <TraceCard key={item.label} title={item.label} detail={item.detail} />)}</div></div></section>
      <section id="trail" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-12 lg:grid-cols-[0.75fr_1.25fr]"><SectionTitle eyebrow="Proof trail" title="Where the skills have been used" /><div className="space-y-4">{trail.map((item) => <TraceCard key={item.title} title={item.title} subtitle={`${item.place} / ${item.date}`} detail={item.detail} />)}</div></div></section>
      <ScreenshotLightbox />
      <CertificateActivitySection activity={<><GitHubActivity /><HackChallenge /><Link href="/hack-lab" className="inline-flex items-center gap-2 border border-mint/30 px-4 py-3 font-bold text-mint hover:bg-mint hover:text-ink">Open full hack lab<ArrowUpRight size={16} /></Link></>} />
      <section className="border-y border-white/10 bg-white/[0.025]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><SectionTitle eyebrow="Download center" title="Everything important in one place" /><div className="mt-8 grid gap-3 sm:grid-cols-2">{downloads.map((item) => { const Icon = item.icon; return <a key={item.label} href={item.href} target={item.href.startsWith("http") ? "_blank" : undefined} rel={item.href.startsWith("http") ? "noreferrer" : undefined} className="flex items-center gap-3 border border-white/10 bg-panel/70 p-4 text-sm text-white/70 transition hover:border-mint hover:text-mint"><Icon size={18} />{item.label}</a>; })}</div></div><div><SectionTitle eyebrow="Achievements ledger" title="Receipts worth keeping visible" /><div className="mt-8 grid gap-2">{achievements.map((item) => <div key={item} className="flex items-center gap-3 border border-white/10 bg-panel/70 p-3 text-sm text-white/68"><BadgeCheck size={17} className="shrink-0 text-mint" />{item}</div>)}</div></div></div></section>
      <section id="waskizone" className="border-y border-white/10 bg-white/[0.025]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[0.82fr_1.18fr] lg:px-8"><div><p className="font-mono text-sm uppercase text-mint">WaskiZone</p><h2 className="mt-3 text-4xl font-black text-white md:text-5xl">Software and cybersecurity services under one practical brand.</h2><p className="mt-5 text-sm leading-7 text-white/62">{waskiZone.positioning}</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/waskizone" className="inline-flex items-center gap-2 bg-mint px-5 py-3 font-bold text-ink hover:bg-white">Explore WaskiZone<ArrowUpRight size={18} /></Link><a href="mailto:juliusmcbrahamsomuah@gmail.com?subject=WaskiZone%20project%20inquiry" className="inline-flex items-center gap-2 border border-white/18 px-5 py-3 font-bold text-white hover:border-cyan hover:text-cyan">Request service</a></div></div><div className="border border-white/10 bg-panel/70 p-5"><Image src="/brand/waskizone/logo/horizontal.png" alt="WaskiZone logo" width={2172} height={724} className="w-full" /><div className="mt-5 grid gap-3 sm:grid-cols-3"><MiniMetric icon={<BadgeCheck size={16} />} label="Now" value="Software" /><MiniMetric icon={<Radar size={16} />} label="Edge" value="Security-aware" /><MiniMetric icon={<Users size={16} />} label="Fit" value="Small teams" /></div></div></div></section>
      <section id="contact" className="border-t border-white/10 bg-ink"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[1fr_1fr] lg:px-8"><div><p className="font-mono text-sm text-mint">Let us build something useful</p><h2 className="mt-3 text-4xl font-black text-white md:text-5xl">Need someone who can ship the backend and think about the attack surface?</h2><p className="mt-5 max-w-xl text-sm leading-7 text-white/62">Reach out for backend/API work, secure integration, project collaboration, mentoring, or practical technical training.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><ContactLink icon={<Mail size={18} />} label="Email" href="mailto:juliusmcbrahamsomuah@gmail.com" value="juliusmcbrahamsomuah@gmail.com" /><ContactLink icon={<Linkedin size={18} />} label="LinkedIn" href="https://www.linkedin.com/in/khophisnow" value="linkedin.com/in/khophisnow" /></div></div><div className="grid gap-5"><ContactIntentSelector /><ContactForm /><DashboardPreviewLink /></div></div></section>
      <footer className="border-t border-white/10 bg-black px-5 py-6 text-center text-xs text-white/45"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-4"><span className="inline-flex items-center gap-2"><MapPin size={14} /> Cape Coast, Ghana</span><span className="inline-flex items-center gap-2"><BadgeCheck size={14} /> Backend APIs / secure systems / training</span><span className="inline-flex items-center gap-2"><Users size={14} /> CAS-7 Technology / Amalitech Coding Club</span></div></footer>
    </main>
  );
}

function SectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div><p className="font-mono text-sm uppercase text-mint">{eyebrow}</p><h2 className="mt-3 max-w-3xl text-3xl font-black leading-tight text-white md:text-5xl">{title}</h2></div>; }
function MiniMetric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="border border-white/10 bg-white/[0.035] p-3"><span className="flex items-center gap-2 text-mint">{icon}<span className="font-mono text-xs">{label}</span></span><span className="mt-2 block text-xs text-white/62">{value}</span></div>; }
function BackendModuleMap({ modules }: { modules: readonly string[] }) { return <div className="mt-5"><p className="font-mono text-xs uppercase text-mint">Backend module map</p><div className="mt-3 flex flex-wrap gap-2">{modules.map((module) => <span key={module} className="border border-white/10 bg-black/25 px-2.5 py-1.5 font-mono text-xs text-white/58">{module}</span>)}</div></div>; }
function TraceCard({ title, detail, subtitle }: { title: string; detail: string; subtitle?: string }) { return <article className="trace-line grid gap-4 border border-white/10 bg-panel/75 p-5 sm:grid-cols-[44px_1fr]"><div className="relative z-10 flex size-11 items-center justify-center border border-mint/30 bg-mint/10 text-mint"><KeyRound size={18} /></div><div><h3 className="text-xl font-black text-white">{title}</h3>{subtitle && <p className="mt-1 text-sm text-cyan">{subtitle}</p>}<p className="mt-3 text-sm leading-7 text-white/62">{detail}</p></div></article>; }
function ContactLink({ icon, label, value, href }: { icon: React.ReactNode; label: string; value: string; href: string }) { return <a href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noreferrer" : undefined} className="border border-white/10 bg-panel/70 p-4 transition hover:border-mint/45"><span className="flex items-center gap-2 text-mint">{icon}<span className="font-mono text-xs">{label}</span></span><span className="mt-3 block break-words text-sm text-white/70">{value}</span></a>; }
